// Code generated by goctl. DO NOT EDIT.
package handler

import (

	"mihoyo-sign/app/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
		},
	)
}
